"""delete keys 'flow_name' and 'flow_run_id' from MLModel

Revision ID: 752367e53636
Revises: ffe669da8cfb
Create Date: 2023-08-12 11:06:51.379512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752367e53636'
down_revision = 'ffe669da8cfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_models_flow_name', table_name='models')
    op.drop_index('ix_models_flow_run_id', table_name='models')
    op.drop_column('models', 'flow_run_id')
    op.drop_column('models', 'flow_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('flow_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('models', sa.Column('flow_run_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_models_flow_run_id', 'models', ['flow_run_id'], unique=False)
    op.create_index('ix_models_flow_name', 'models', ['flow_name'], unique=False)
    # ### end Alembic commands ###
