"""adds columns to file table

Revision ID: b3f866061559
Revises: d6db58ab0afa
Create Date: 2023-07-07 09:28:51.305630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f866061559'
down_revision = 'd6db58ab0afa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
