"""adds key path and size into file table

Revision ID: d6db58ab0afa
Revises: f74ea318f723
Create Date: 2023-07-04 12:18:32.539743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6db58ab0afa'
down_revision = 'f74ea318f723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('size', sa.String(), nullable=True))
    op.add_column('files', sa.Column('path', sa.String(), nullable=True))
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.create_index(op.f('ix_files_size'), 'files', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_size'), table_name='files')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_column('files', 'path')
    op.drop_column('files', 'size')
    # ### end Alembic commands ###
