"""add mlmodel class

Revision ID: e7cfd895a4f6
Revises: a1abb61e99cd
Create Date: 2023-07-27 14:40:03.316865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cfd895a4f6'
down_revision = 'a1abb61e99cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('flow_run_id', sa.Integer(), nullable=True),
    sa.Column('flow_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_description'), 'models', ['description'], unique=False)
    op.create_index(op.f('ix_models_flow_name'), 'models', ['flow_name'], unique=False)
    op.create_index(op.f('ix_models_flow_run_id'), 'models', ['flow_run_id'], unique=False)
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=True)
    op.add_column('files', sa.Column('labeled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_files_labeled'), 'files', ['labeled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_labeled'), table_name='files')
    op.drop_column('files', 'labeled')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_index(op.f('ix_models_flow_run_id'), table_name='models')
    op.drop_index(op.f('ix_models_flow_name'), table_name='models')
    op.drop_index(op.f('ix_models_description'), table_name='models')
    op.drop_table('models')
    # ### end Alembic commands ###
