"""adds keys to file table

Revision ID: f2b735d809cb
Revises: b3f866061559
Create Date: 2023-07-07 09:38:00.637589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b735d809cb'
down_revision = 'b3f866061559'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('ADC', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('RAD', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('RA', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('AD', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('RD', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('spectrogram', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('radarPC', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('lidarPC', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('image', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('config', sa.String(), nullable=True))
    op.add_column('files', sa.Column('parse', sa.String(), nullable=True))
    op.create_index(op.f('ix_files_AD'), 'files', ['AD'], unique=False)
    op.create_index(op.f('ix_files_ADC'), 'files', ['ADC'], unique=False)
    op.create_index(op.f('ix_files_RA'), 'files', ['RA'], unique=False)
    op.create_index(op.f('ix_files_RAD'), 'files', ['RAD'], unique=False)
    op.create_index(op.f('ix_files_RD'), 'files', ['RD'], unique=False)
    op.create_index(op.f('ix_files_config'), 'files', ['config'], unique=False)
    op.create_index(op.f('ix_files_image'), 'files', ['image'], unique=False)
    op.create_index(op.f('ix_files_lidarPC'), 'files', ['lidarPC'], unique=False)
    op.create_index(op.f('ix_files_parse'), 'files', ['parse'], unique=False)
    op.create_index(op.f('ix_files_radarPC'), 'files', ['radarPC'], unique=False)
    op.create_index(op.f('ix_files_spectrogram'), 'files', ['spectrogram'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_spectrogram'), table_name='files')
    op.drop_index(op.f('ix_files_radarPC'), table_name='files')
    op.drop_index(op.f('ix_files_parse'), table_name='files')
    op.drop_index(op.f('ix_files_lidarPC'), table_name='files')
    op.drop_index(op.f('ix_files_image'), table_name='files')
    op.drop_index(op.f('ix_files_config'), table_name='files')
    op.drop_index(op.f('ix_files_RD'), table_name='files')
    op.drop_index(op.f('ix_files_RAD'), table_name='files')
    op.drop_index(op.f('ix_files_RA'), table_name='files')
    op.drop_index(op.f('ix_files_ADC'), table_name='files')
    op.drop_index(op.f('ix_files_AD'), table_name='files')
    op.drop_column('files', 'parse')
    op.drop_column('files', 'config')
    op.drop_column('files', 'image')
    op.drop_column('files', 'lidarPC')
    op.drop_column('files', 'radarPC')
    op.drop_column('files', 'spectrogram')
    op.drop_column('files', 'RD')
    op.drop_column('files', 'AD')
    op.drop_column('files', 'RA')
    op.drop_column('files', 'RAD')
    op.drop_column('files', 'ADC')
    # ### end Alembic commands ###
