"""add key parent_id into MLModel

Revision ID: ffe669da8cfb
Revises: 126cf2a6b333
Create Date: 2023-08-11 18:40:37.583394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe669da8cfb'
down_revision = '126cf2a6b333'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_models_parent_id'), 'models', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_parent_id'), table_name='models')
    op.drop_column('models', 'parent_id')
    # ### end Alembic commands ###
